# Generated by Django 5.2.13 on 2026-04-19 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('schools', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teacher',
            name='teachers_te_school__e5d1bf_idx',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='exams.subject'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school'], name='teachers_te_school__56510d_idx'),
        ),
    ]
