# Generated by Django 6.0.4 on 2026-08-07 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0003_remove_teacher_subject_teacher_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="basic_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
