# Generated by Django 6.0.4 on 2026-08-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0004_teacher_basic_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="designation",
            field=models.CharField(blank=True, default="Teacher", max_length=50),
        ),
    ]
