# Generated by Django 6.0.4 on 2026-08-07 15:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        ("teachers", "0004_teacher_basic_salary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary_month", models.CharField(max_length=7)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("pending", "Pending"),
                            ("partial", "Partial"),
                            ("hold", "On Hold"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("online", "Online Transfer"),
                            ("cheque", "Cheque"),
                            ("dd", "Demand Draft"),
                        ],
                        default="cash",
                        max_length=10,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("remarks", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_salary_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_payments",
                        to="schools.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_payments",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_salarypayment",
                "indexes": [
                    models.Index(
                        fields=["school", "status"],
                        name="payroll_sal_school__41f830_idx",
                    ),
                    models.Index(
                        fields=["teacher", "salary_month"],
                        name="payroll_sal_teacher_ddecc8_idx",
                    ),
                ],
            },
        ),
    ]
