# Generated by Django 5.2.13 on 2026-04-22 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('leave_request', 'Leave Request'), ('transfer_request', 'Transfer Request'), ('fee_waiver', 'Fee Waiver'), ('scholarship', 'Scholarship'), ('other', 'Other')], default='leave_request', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('teacher_reviewed', 'Teacher Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('teacher_review', models.TextField(blank=True, null=True)),
                ('teacher_decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', help_text='For leave requests, teacher makes final decision', max_length=20)),
                ('teacher_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_review', models.TextField(blank=True, null=True)),
                ('admin_decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('admin_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_reviewed_as_admin', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student')),
                ('teacher_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_reviewed_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applications_application',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'created_at'], name='application_school__56a964_idx'), models.Index(fields=['student', 'status'], name='application_student_7f76d3_idx'), models.Index(fields=['application_type', 'status'], name='application_applica_15d90b_idx')],
            },
        ),
    ]
