# Generated by Django 6.0.4 on 2026-08-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='category',
            field=models.CharField(choices=[('tuition', 'Tuition'), ('library', 'Library'), ('transport', 'Transport'), ('hostel', 'Hostel'), ('exam', 'Examination'), ('other', 'Other')], default='tuition', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('school', 'class_name', 'academic_year', 'category')},
        ),
    ]
