# Generated by Django 6.0.4 on 2026-08-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feestructure_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='frequency',
            field=models.CharField(choices=[('one_time', 'One-Time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('annual', 'Annual')], default='annual', max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='category',
            field=models.CharField(default='tuition', max_length=50),
        ),
    ]
